[package]
name = "synth"
version = "0.2.0"
authors = ["dzil123 <5725958+dzil123@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hound = "~3.4.0"
rand = "~0.8.1"
rustc-hash = "~1.1.0"
wmidi = "~4.0.1"
midir = "~0.7.0"

[dependencies.rodio]
version = "~0.13.0"
default_features = false
